local harpoon = require 'harpoon'

vim.keymap.set('n', '<leader>a', function()
  harpoon:list():add()
end, { desc = 'Add file to Harpoon' })
vim.keymap.set('n', '<C-q>', function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set('n', '<leader>j', function()
  harpoon:list():select(1)
end, { desc = 'HARPOON - Go to first file' })
vim.keymap.set('n', '<leader>k', function()
  harpoon:list():select(2)
end, { desc = 'HARPOON - Go to second file' })
vim.keymap.set('n', '<leader>l', function()
  harpoon:list():select(3)
end, { desc = 'HARPOON - Go to third file' })
vim.keymap.set('n', '<leader>;', function()
  harpoon:list():select(4)
end, { desc = 'HARPOON - Go to fourth file' })
